# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
    ]
